// <auto-generated />
using System;
using LicitacoesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace licitacaoApi.Migrations
{
    [DbContext(typeof(LicitacaoContext))]
    [Migration("20250602142708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LicitacaoAPI.Models.Licitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoComprador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataHoraAberturaProcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraFimPropostas")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraInicioPropostas")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroLicitacao")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NumeroLicitacao")
                        .IsUnique();

                    b.ToTable("Licitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
